# Generated by Django 4.2.5 on 2023-10-26 02:49

import app_EcoBinLocator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_EcoBinLocator', '0005_denuncia_cidade_denuncia_pr_denuncia_rua_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=app_EcoBinLocator.models.upload_image),
        ),
    ]
