# Generated by Django 4.2.5 on 2023-10-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_EcoBinLocator', '0002_alter_usuario_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.TextField(max_length=255)),
                ('numero', models.CharField(max_length=255)),
            ],
        ),
    ]
