# Generated by Django 4.2.5 on 2023-10-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_EcoBinLocator', '0003_endereco'),
    ]

    operations = [
        migrations.CreateModel(
            name='denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('den', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='suporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sup', models.TextField(max_length=255)),
            ],
        ),
    ]
