# Generated by Django 4.2.5 on 2023-10-02 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_EcoBinLocator', '0004_denuncia_suporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='cidade',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='pr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='rua',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='telefone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='den',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
